name: 'breakout_ppo'


env:
  name: vel.rl.env.classic_atari
  game: 'BreakoutNoFrameskip-v4'


vec_env:
  name: vel.rl.vecenv.shared_mem
  frame_history: 4  # How many stacked frames go into a single observation


model:
  name: vel.rl.models.stochastic_policy_model

  input_block:
    name: vel.modules.input.image_to_tensor

  backbone:
    name: vel.rl.models.backbone.nature_cnn
    input_width: 84
    input_height: 84
    input_channels: 4  # The same as frame_history


reinforcer:
  name: vel.rl.reinforcers.on_policy_iteration_reinforcer

  algo:
    name: vel.rl.algo.policy_gradient.ppo

    entropy_coefficient: 0.01
    value_coefficient: 0.5

    discount_factor: 0.99 # Discount factor for the rewards
    gae_lambda: 0.95 # Generalized Advantage Estimator Lambda parameter

    max_grad_norm: 0.5 # Gradient clipping parameter

    cliprange:
      name: vel.schedules.linear
      initial_value: 0.1
      final_value: 0.0

  env_roller:
    name: vel.rl.env_roller.step_env_roller

  parallel_envs: 8 # How many environments to run in parallel
  number_of_steps: 128 # How many environment steps go into a single batch
  batch_size: 256 # How many samples can go into the model once
  experience_replay: 4 # How many times to replay the experience


optimizer:
  name: vel.optimizers.adam
  lr: 2.5e-4
  epsilon: 1.0e-5


scheduler:
  name: vel.scheduler.linear_batch_scaler


commands:
  train:
    name: vel.rl.commands.rl_train_command
    total_frames: 1.1e7
    batches_per_epoch: 10

  record:
    name: vel.rl.commands.record_movie_command
    takes: 10
    videoname: 'breakout_ppo_vid_{:04}.avi'

  evaluate:
    name: vel.rl.commands.evaluate_env_command
    parallel_envs: 16 # How many environments to run in parallel

    takes: 20
