name: 'half_cheetah_trpo'

env:
  name: vel.rl.env.mujoco
  game: 'HalfCheetah-v2'
  normalize_returns: true


vec_env:
  name: vel.rl.vecenv.dummy


model:
  name: vel.rl.models.stochastic_policy_model_separate

  input_block:
    name: vel.modules.input.normalize_observations
    input_shape: 17

  policy_backbone:
    name: vel.rl.models.backbone.mlp
    input_length: 17
    hidden_layers: [32, 32]
    activation: 'tanh'

  value_backbone:
    name: vel.rl.models.backbone.mlp
    input_length: 17
    hidden_layers: [32, 32]
    activation: 'tanh'


reinforcer:
  name: vel.rl.reinforcers.on_policy_iteration_reinforcer

  algo:
    name: vel.rl.algo.policy_gradient.trpo
    discount_factor: 0.99 # Discount factor for the rewards
    gae_lambda: 0.98 # Generalized Advantage Estimator Lambda parameter

    max_kl: 0.01
    cg_iters: 10
    line_search_iters: 10
    improvement_acceptance_ratio: 0.1
    cg_damping: 0.1
    vf_iters: 5
    entropy_coef: 0.0
#    max_grad_norm: 0.5

  env_roller:
    name: vel.rl.env_roller.step_env_roller

  parallel_envs: 1 # How many environments to run in parallel
  number_of_steps: 1024 # How many environment steps go into a single batch
  batch_size: 1024 # How many samples can go into the model once
#  experience_replay: 10 # How many times to replay the experience



optimizer:
  name: vel.optimizers.adam
  lr: 1.0e-3
  epsilon: 1.0e-8


#scheduler:
#  name: vel.scheduler.linear_batch_scaler


commands:
  train:
    name: vel.rl.commands.rl_train_command
    total_frames: 1.0e6
    batches_per_epoch: 4

  record:
    name: vel.rl.commands.record_movie_command
    takes: 10
    videoname: 'reacher_vid_{:04}.avi'
    sample_args:
      argmax_sampling: true
