name: 'seaquest_acer'


env:
  name: vel.rl.env.classic_atari
  game: 'SeaquestNoFrameskip-v4'


vec_env:
  name: vel.rl.vecenv.shared_mem
  frame_history: 4  # How many stacked frames go into a single observation


model:
  name: vel.rl.models.q_stochastic_policy_model

  input_block:
    name: vel.modules.input.image_to_tensor

  backbone:
    name: vel.rl.models.backbone.nature_cnn
    input_width: 84
    input_height: 84
    input_channels: 4  # The same as frame_history


reinforcer:
  name: vel.rl.reinforcers.buffered_mixed_policy_iteration_reinforcer

  env_roller:
    name: vel.rl.env_roller.trajectory_replay_env_roller

    replay_buffer:
      name: vel.rl.buffers.circular_replay_buffer

      buffer_initial_size: 1_000 # How many samples we need in the buffer before we start using replay buffer
      buffer_capacity: 50_000

      # Because env has a framestack already built-in, save memory by encoding only last frames in the replay buffer
      frame_stack_compensation: true
      frame_history: 4  # How many stacked frames go into a single observation

  algo:
    name: vel.rl.algo.policy_gradient.acer
    entropy_coefficient: 0.01
    q_coefficient: 0.5
    rho_cap: 10.0
    retrace_rho_cap: 1.0

    max_grad_norm: 10.0
    discount_factor: 0.99

    trust_region: true
    trust_region_delta: 1.0

  parallel_envs: 12 # How many environments to run in parallel
  number_of_steps: 20 # How many environment steps go into a single batch
  experience_replay: 4


optimizer:
  name: vel.optimizers.rmsprop
  lr: 7.0e-4
  alpha: 0.99
  #  epsilon: 1.0e-5
  epsilon: 1.0e-3


commands:
  train:
    name: vel.rl.commands.rl_train_command
    total_frames: 1.1e7
    batches_per_epoch: 10

  record:
    name: vel.rl.commands.record_movie_command
    takes: 10
    videoname: 'seaquest_vid_{:04}.avi'

  evaluate:
    name: vel.rl.commands.evaluate_env_command
    takes: 100
    parallel_envs: 12 # How many environments to run in parallel
