name: 'reacher_a2c'


env:
  name: vel.rl.env.mujoco
  game: 'Reacher-v2'
  normalize_returns: true


vec_env:
  name: vel.rl.vecenv.dummy


model:
  name: vel.rl.models.stochastic_policy_model

  input_block:
    name: vel.modules.input.normalize_observations
    input_shape: 11

  backbone:
    name: vel.rl.models.backbone.mlp
    input_length: 11
    hidden_layers: [64, 64]
    activation: 'tanh'


reinforcer:
  name: vel.rl.reinforcers.on_policy_iteration_reinforcer

  algo:
    name: vel.rl.algo.policy_gradient.a2c

    entropy_coefficient: 0.0
    value_coefficient: 0.5
    max_grad_norm: 0.5

    gae_lambda: 0.95 # Generalized Advantage Estimator Lambda parameter
    discount_factor: 0.99 # Discount factor for the rewards

  env_roller:
    name: vel.rl.env_roller.step_env_roller

  parallel_envs: 1 # How many environments to run in parallel
  number_of_steps: 2048 # How many environment steps go into a single batch
  batch_size: 2048 # How many samples can go into the model once


optimizer:
  name: vel.optimizers.adam
  lr: 3.0e-4
  epsilon: 1.0e-5



commands:
  train:
    name: vel.rl.commands.rl_train_command
    total_frames: 1.0e6
    batches_per_epoch: 1

  record:
    name: vel.rl.commands.record_movie_command
    takes: 10
    videoname: 'reacher_vid_{:04}.avi'
    sample_args:
      argmax_sampling: true
